---
# file: site.yml
# Master playbook for hadoop

# Gather facts first:
- hosts: all

- hosts: namenode
  sudo: yes
  tasks:
  - name: Create hadoop group
    group: name=hadoop

  - name: Create hadoop user
    user: name=hadoop group=hadoop shell=/bin/bash generate_ssh_key=yes

  - name: Fetch the generated key
    fetch: src=/home/hadoop/.ssh/id_rsa.pub dest=/tmp/hadoop.id_rsa.pub flat=yes

- hosts: all
  sudo: yes
  roles: [common]

- hosts: namenode
  sudo: yes
  sudo_user: hadoop
  roles: [namenode]

- hosts: client
  tags: client
  roles: [client]  
