---
# file: roles/namenode/main.yml

- name: Update APT package cache and upgrade APT to the latest packages
  apt: update_cache=yes cache_valid_time=3600

- name: Installs rsync
  apt: name=rsync

- name: Installs java
  apt: name=openjdk-7-jdk

- name: Create hadoop group
  group: name=hadoop

- name: Create hadoop user
  user: name=hadoop group=hadoop shell=/bin/bash generate_ssh_key=yes

- name: Add passphraseless localhost login by adding the generated key to authorized_keys
  authorized_key: user=hadoop key="{{ lookup('file', '/tmp/hadoop.id_rsa.pub') }}"

- name: download hadoop archive
  get_url: url=http://www.pirbot.com/mirrors/apache/hadoop/common/current/hadoop-2.6.0.tar.gz
    dest=/tmp/hadoop.tar.gz

- name: unpack the archive
  unarchive: src=/tmp/hadoop.tar.gz dest=/opt copy=false
    creates=/opt/hadoop-2.6.0/etc/hadoop

- name: assign ownership
  file: path=/opt/hadoop-2.6.0 owner=hadoop group=hadoop recurse=yes

- name: Specify JAVA_HOME
  sudo_user: hadoop
  lineinfile: dest=/opt/hadoop-2.6.0/etc/hadoop/hadoop-env.sh
    regexp='^export JAVA_HOME='
    line='export JAVA_HOME=/usr/lib/jvm/java-7-openjdk-amd64'

- name: Specify HADOOP_PREFIX
  sudo_user: hadoop
  lineinfile: dest=/opt/hadoop-2.6.0/etc/hadoop/hadoop-env.sh
    line="{{ item }}"
    insertbefore=BOF
  with_items: 
    - "export HADOOP_CONF_DIR=$HADOOP_PREFIX/etc/hadoop"
    - "export HADOOP_HOME=$HADOOP_PREFIX"
    - "export HADOOP_PREFIX=/opt/hadoop-2.6.0"

- name: Augment PATH 
  sudo_user: hadoop
  lineinfile: dest=/opt/hadoop-2.6.0/etc/hadoop/hadoop-env.sh
    line="export PATH=$PATH:$HADOOP_HOME/bin"
    insertafter=EOF

- name: Test the installation
  sudo: no
  shell: ". /opt/hadoop-2.6.0/etc/hadoop/hadoop-env.sh && hadoop version"
  changed_when: false 
  register: cmd_result

- assert:
    that:
      - "'Hadoop 2.6.0' in cmd_result.stdout"

- name: copy configuration
  sudo_user: hadoop
  template: src={{ item }} dest="/opt/hadoop-2.6.0/etc/hadoop/"
  with_items:
    - core-site.xml
    - hdfs-site.xml
